### ISSUE TITLE
Request Release of 1.2.3 version

### ISSUE THREAD

**Issue by javimaravillas** [ApeWorX/eth-abi#112]
I request a release of 1.2.3 as https://github.com/ethereum/eth-abi/pull/110 has been merged and it is needed for fixing https://github.com/ethereum/py-evm/issues/1484

@davesque can you help?

**Comment by davesque** [comment]
Yep, I'll do that now.

**Comment by davesque** [comment]
I'm going to make this release 1.3.0 since that seems more appropriate when updating a dependency's major version requirement.

**Comment by davesque** [comment]
Okay, just released 1.3.0.
