### ISSUE TITLE
`bytes32` is decoded as a unicode string

### ISSUE THREAD

**Issue by Arachnid** [ApeWorX/eth-abi#13]
### What was wrong?
`bytes32` arguments in ABIs are decoded as null-terminated unicode strings, although they often don't contain text data.

### How was it fixed?
`bytes32` should be represented as a 64-character hex string, instead.

#### Cute Animal Picture

http://news.nationalgeographic.com/content/dam/news/2016/07/19/slothlove/01_slothlove_leaves.jpg

**Comment by carver** [comment]
Fixed in https://github.com/ethereum/eth-abi/commit/cb92f558310f3719847a965d58c9bf3547027d8d and merged with https://github.com/ethereum/eth-abi/pull/28

Instead of trying to decode to a unicode string, the bytes decoder now outputs a `bytes` value.
