### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by byzantineninja** [ApeWorX/eth-abi#131]
* Version: 1.3.0
* Python: 3.7
* OS: osx/linux/win

* result of `pip freeze | grep eth`

eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.5.2
prometheus-client==0.3.1
pyethereum==1.0.0

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
```
import eth_abi
```

* The full output of the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\Lib\site-packages\eth_abi\__init__.py", line 3, in <module>
    from eth_abi.abi import (  # NOQA
  File "C:\Python37\Lib\site-packages\eth_abi\abi.py", line 4, in <module>
    from eth_utils import (
  File "C:\Python37\Lib\site-packages\eth_utils\__init__.py", line 5, in <module>
    from .abi import (  # noqa: F401
  File "C:\Python37\Lib\site-packages\eth_utils\abi.py", line 1, in <module>
    from typing import Any, Dict
  File "C:\Python37\Lib\site-packages\typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "C:\Python37\Lib\site-packages\typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by byzantineninja** [comment]
I solved this problem with ` pip uninstall typing`

**Comment by carver** [comment]
Yup, we only test against the built-in typing library. Closing as not a bug. Thanks for the report and the follow-up!

**Comment by jordanmkoncz** [comment]
When using Pip version 20.1 (released 29/04/2020), the solution of uninstalling the `typing` package no longer works for some reason. An easy workaround is to ensure you're using the previous version of Pip, 20.0.2, where this solution still works.

**Comment by hs-ye** [comment]
PSA: So it turns out that the extra typing package is redundant after py 3.6 and is only used to backport this functionality in earlier versions. https://pypi.org/project/typing/

Can safely uninstall this if you are using any later versions of python.

**Comment by carver** [comment]
> When using Pip version 20.1 (released 29/04/2020), the solution of uninstalling the `typing` package no longer works for some reason. An easy workaround is to ensure you're using the previous version of Pip, 20.0.2, where this solution still works.

Hm, yeah, I've notice a couple bugs in recent versions of pip. An upgrade to latest pip/setuptools, plus wiping away and re-building a venv did the trick. So that's another thing to try, especially in this case, if you have a `typing` uninstall that isn't helping.

**Comment by moriyoshi** [comment]
https://github.com/pypa/pip/issues/8272

**Comment by Arindam-Jain** [comment]
> I solved this problem with ` pip uninstall typing`

God bless you thanks very much

**Comment by jayanti-prasad** [comment]
> I solved this problem with ` pip uninstall typing`

yes it works !

**Comment by carver** [comment]
Glad that people were finding the tips in this issue as helpful. The "thanks" comments ping us, so I'm locking the thread for now. Feel free to pile onto the emojis for the helpful comment to give your thanks. :)
