### ISSUE TITLE
Doctest failed on the version bump to v2

### ISSUE THREAD

**Issue by carver** [ApeWorX/eth-abi#134]
### What was wrong?

The CI build badge is showing red in the readme, because of this failure:
https://circleci.com/gh/ethereum/eth-abi/2086?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @davesque

### How can it be fixed?

:man_shrugging:

**Comment by davesque** [comment]
Looks like some tests based on RNG are failing.  I guess my method for ensuring the same seed isn't working (or stopped working?).  Either way, I'll take a look.

**Comment by davesque** [comment]
I went ahead and just removed the lines which generate test examples.  I think it's clear enough what the code is doing without it.  I also went cowboy and just merged it straight into master so another PR I just made would stop failing.  Sorry! :)

**Comment by carver** [comment]
Yikes! Not sure the situation justified that, I think you would have gotten pretty quick :+1: on merging a PR.

Anyhow, can you link the commit in this issue?

**Comment by davesque** [comment]
Sure: https://github.com/ethereum/eth-abi/commit/e043f730b5acbf76169d8d1cabf99b1d7a4d96bf

**Comment by davesque** [comment]
As you can see, I just deleted some lines from a doctest. I dunno, I assumed this fits under the "pedantic to request approval" category. :/
