### ISSUE TITLE
Updating to hypothesis > 4 to fix python 3.8 compatibility

### ISSUE THREAD

**Issue by step21** [ApeWorX/eth-abi#143]
## What was wrong?
installing / testing on python 3.8 give this error https://github.com/HypothesisWorks/hypothesis/issues/1943

### Code that produced the error

It is fixed in hypothesis, but not in a version supported by eth-abi per current requirements.

### Expected Result

working properly with python 3.8

## How can it be fixed?

Allow hypothesis > 4 and see if it works...

**Comment by kclowes** [comment]
Closed with #145
