### ISSUE TITLE
pip install broken for 0.4.5

### ISSUE THREAD

**Issue by fuzzyami** [ApeWorX/eth-abi#22]
* Version: 0.4.5
* Python: 2.7
* OS: linux, macos

pip install fails with the following output:

➜  kinawardservice git:(master) ✗ sudo pip install ethereum-abi-utils --upgrade

The directory '/Users/amiblonder/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/amiblonder/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Collecting ethereum-abi-utils
  Downloading ethereum-abi-utils-0.4.5.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs/setuptools_markdown-0.2-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.4
    Downloading https://pypi.python.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz#md5=28d28cf8f1942abf680c040707cee55a
    Processing pypandoc-1.4.tar.gz
    Writing /tmp/easy_install-c6FpMb/pypandoc-1.4/setup.cfg
    Running pypandoc-1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-c6FpMb/pypandoc-1.4/egg-dist-tmp-Rubecs
    Maybe try:

        brew install pandoc
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------

    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__

    !!! pandoc not found, long_description is bad, don't upload this to PyPI !!!

    creating /private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs/pypandoc-1.4-py2.7.egg
    Extracting pypandoc-1.4-py2.7.egg to /private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs

    Installed /private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs/pypandoc-1.4-py2.7.egg
    Searching for wheel>=0.25.0
    Reading https://pypi.python.org/simple/wheel/
    Best match: wheel 0.30.0
    Downloading https://pypi.python.org/packages/fa/b4/f9886517624a4dcb81a1d766f68034344b7565db69f13d52697222daeb72/wheel-0.30.0.tar.gz#md5=e48f8f2329f1419572d93b68a63272a9
    Processing wheel-0.30.0.tar.gz
    Writing /tmp/easy_install-XliS_m/wheel-0.30.0/setup.cfg
    Running wheel-0.30.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-XliS_m/wheel-0.30.0/egg-dist-tmp-5IAHAX
    warning: no files found matching 'wheel/*.txt'
    warning: no files found matching '*.py' under directory 'wheel/test'
    warning: no files found matching 'wheel/test/test-1.0-py2.py3-none-win32.whl'
    warning: no files found matching 'wheel/test/headers.dist/header.h'
    warning: no files found matching 'wheel/test/pydist-schema.json'
    no previously-included directories found matching 'wheel/test/*/dist'
    no previously-included directories found matching 'wheel/test/*/build'
    creating /private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs/wheel-0.30.0-py2.7.egg
    Extracting wheel-0.30.0-py2.7.egg to /private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs

    Installed /private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs/wheel-0.30.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-XVffAh/ethereum-abi-utils/setup.py", line 33, in <module>
        'Programming Language :: Python :: 3.5',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/private/tmp/pip-build-XVffAh/ethereum-abi-utils/.eggs/pypandoc-1.4-py2.7.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-XVffAh/ethereum-abi-utils/

**Comment by pipermerriam** [comment]
You need to update your dependency to either use `eth-abi` which is what this library was renamed to or pin to `ethereum-abi-utils<0.4.5`.  The python library `ethereum-abi-utils` will no longer receive any updates.  All future development is under the python library `eth-abi`

Also, you should upgrade to python3 **really** soon as support for python2 drops at the beginning of 2018.

**Comment by fuzzyami** [comment]
thanks for the prompt reply!

**Comment by pipermerriam** [comment]
the stub package for `ethereum-abi-utils` which redirects users to `eth-abi` has been updated to work on python2.7
