### ISSUE TITLE
eth-utils dependency conflicts with other eth-* packages

### ISSUE THREAD

**Issue by mbeacom** [ApeWorX/eth-abi#25]
* Version: 0.5.0
* Python: 3.5/3.6
* OS: osx/linux

### What was wrong?

Currently, the https://github.com/gitcoinco/web repository Travis builds are failing due to a dependency conflict with other `eth-` packages. 
Explanation: https://github.com/gitcoinco/web/issues/367

Validation is failing due to a conflict in dependencies:

- eth-keys and eth-keyfile pins eth-utils<2.0.0,>=1.0.0-beta.1
- eth-abi pins `eth-utils==0.7.*`

This seems to cause the build to fail dependency validation.

### How can it be fixed?

- Update `eth-abi` to use` >=1.0.0b1` of the `eth-utils` package?

#### Note

It appears `eth-tester` is resulting in the same error due to pinning `<1.0.0`

**Comment by carver** [comment]
@mbeacom thanks for highlighting this. There are a few things wrong here, all of which should be fixed eventually. But the most important thing is that some beta dependencies slipped into web3.py v3 stable, so I'll start with that.

- [x] remove (erroneous) dependency on eth-keys, eth-keyfile, (others?) in v3 **this fix alone should solve the issue**

Other things that should be attended to:
- [ ] release a version of eth-abi that supports eth-utils v1
- [ ] release a version of eth-tester that supports eth-utils v1

**Comment by carver** [comment]
Most importantly for this issue:

`web3` v3.16.5 is released, and will no longer try to install eth-utils v1. Please report back whether you're all set @mbeacom 

---

Other upcoming releases:

- `eth-abi` v1.0.0-beta.0 to support eth-utils v1
- `eth-tester` v0.1.0-beta.16 to support eth-utils v1

**Comment by mbeacom** [comment]
@carver 🙌 Your changes resolved the dependency issues! Thanks for your work on this!

**Comment by mbeacom** [comment]
@carver Any chance these changes will be ported to web3.py 4.x.x?

Thanks again

**Comment by carver** [comment]
It will get fixed in v4, but in a totally different way: releasing versions of eth-abi and eth-tester that are compatible with eth-utils v1-beta. I will try to get that out today.

**Comment by mbeacom** [comment]
@carver Thanks for taking care of this! Let me know if there is anything I can do!

**Comment by carver** [comment]
If everything goes to plan (famous last words), the next v4 will be released tomorrow.

**Comment by carver** [comment]
Ok, released: http://web3py.readthedocs.io/en/latest/releases.html#v4-0-0-beta-9
(everything did not go according to plan 😆 )

Please reopen/comment if the issue persists

**Comment by hiqua** [comment]
There seems to be other conflicts between libraries that `pipenv` does not install without the `--skip-lock` flag: `pipenv install web3` fails with
```Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.```

After that, `pipenv install --skip-lock` succeeds, but installs a version of `eth-utils` which is not (supposed to be) compatible with `eth-abi`.

**Comment by carver** [comment]
@hiqua can you try `pipenv clean && pipenv lock --clear && pipenv sync` mentioned here: https://github.com/pypa/pipenv/issues/1802#issuecomment-375026954

Then try using `pipenv install --pre web3==v4.0.0b11` to get the latest. I don't know why, but  `pipenv install --pre web3` was not working for me. After seeing the other `pipenv` weirdnesses, I didn't investigate.

**Comment by hiqua** [comment]
The following:
```sh
#!/bin/sh
mkdir web3test
cd web3test
pipenv install web3 || pipenv install --skip-lock

pipenv clean && pipenv lock --clear && pipenv sync
echo "Trying to install the latest"
pipenv install --pre web3==v4.0.0b11
```

fails.

Trying
```sh
pipenv install --pre web3==v4.0.0b11
```
directly without anything before fails as well.

I don't know how bug-free pipenv is though, I just know that it is "the officially recommended Python packaging tool", so I thought it might be relevant.

**Comment by oryband** [comment]
I can confirm this occurs for me as well. Please reopen this issue.

**Comment by hiqua** [comment]
@oryband if you're talking about the pipenv issue, you can follow the discussion there: https://github.com/pypa/pipenv/issues/1802#issuecomment-375026954

At this point I cannot tell whether it's a bug in pipenv or in web3, and it has its own issue opened there: https://github.com/ethereum/web3.py/issues/707. If you have more information about this issue, I'd be interested as well!

**Comment by CasualEngineerZombie** [comment]
Hi everyone, any solution to this issue?
