### ISSUE TITLE
StringEncoder accepts byte-serialized objects, not a string

### ISSUE THREAD

**Issue by anomit** [ApeWorX/eth-abi#31]
* Version: 0.50
* Python: 3.6.4
* OS: osx

### What was wrong?

I get it that Solidity specifies string to be nothing but a dynamic sized array of bytes, but as a user of a python library, isn't it more intuitive to expect that I can pass a standard Python string to be encoded as a Solidity "string". 

Currently this is the line #410 in [eth_abi/encoding.py](https://github.com/ethereum/eth-abi/blob/655c3bd15952d0b6d7b1efd9d6767be14056217e/eth_abi/encoding.py#L410) 
```
class StringEncoder(BaseEncoder):
    @classmethod
    def encode(cls, value):
        if not is_bytes(value):
            raise EncodingTypeError(
                "Value of type {0} cannot be encoded by StringEncoder".format(
                    type(value),
                )
            )
```

### How can it be fixed?

I would take a shot at the following:
```
if type(value) is not str:
    raise EncodingTypeError(
                "Value of type {0} cannot be encoded by StringEncoder".format(
                    type(value),
                )
            )
serialized_bytes = value.encode('utf-8')
#perform consequent operations on serialized_bytes
```

In any case I would like to understand more on the decision to accept only bytes, the challenges and considerations that were thought of in the first place.

**Comment by pipermerriam** [comment]
This was actually fixed yesterday.  Now there is a `ByteStringEncoder` and a `TextStringEncoder`.  They both restrict the types they allow to `bytes`, `str` respectively.

**Comment by pipermerriam** [comment]
You'll need to install the beta with `pip install --pre eth-abi`
