### ISSUE TITLE
Add type hints and mypy to CI

### ISSUE THREAD

**Issue by pipermerriam** [ApeWorX/eth-abi#33]
### What was wrong?

We should add type hints to the code as well as a `mypy` run to the CI environment.

### How can it be fixed?

Copy implementation from `eth-keys` or `py-evm` repo.

**Comment by palash25** [comment]
Seems like a beginner issue. Would like to take a crack at this.

**Comment by pipermerriam** [comment]
@palash25 go for it.  ALso, you don't have to do the entire library all in one go if you'd like to start by getting `mypy` runs going in CI and only implementing types for a limited subset of the python modules so you can do it iteratively.
