### ISSUE TITLE
Fixed length string type is valid?

### ISSUE THREAD

**Issue by davesque** [ApeWorX/eth-abi#44]
### What was wrong?

It appears that eth-abi considers a string with a fixed length to be a valid type:
https://github.com/ethereum/eth-abi/blob/master/eth_abi/utils/parsing.py#L57-L61

However, eth-abi handles fixed length strings no differently than dynamic-length strings:
https://github.com/ethereum/eth-abi/blob/master/eth_abi/encoding.py#L66-L67
https://github.com/ethereum/eth-abi/blob/master/eth_abi/decoding.py#L52-L53

### How can it be fixed?

Perhaps the type validation code should be updated at some point to throw an error for fixed length strings?

**Comment by pipermerriam** [comment]
Are fixed-length strings a thing?  I wasn't aware of that as a supported type in Solidity (no clue what vyper supports)

**Comment by carver** [comment]
> Are fixed-length strings a thing?

According to the [ABI wiki](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#types), no.

**Comment by davesque** [comment]
Yeah, I couldn't find any reference to a fixed length string type in either the [current](https://solidity.readthedocs.io/en/develop/abi-spec.html) or [legacy](https://github.com/ethereum/wiki/blob/master/Ethereum-Contract-ABI.md#types) documentation for the ABI.

**Comment by davesque** [comment]
Submitted pull request for this: #64

**Comment by davesque** [comment]
Fixed with #64 .
