### ISSUE TITLE
Should zero-length tuple types be a valid type?

### ISSUE THREAD

**Issue by davesque** [ApeWorX/eth-abi#47]
*Note: This issue ticket doesn't follow the usual format because I couldn't think of a way to fit it into that.*

In the [solidity ABI spec](https://solidity.readthedocs.io/en/develop/abi-spec.html#types), it appears that zero-length tuple types are a valid type:

> (T1,T2,...,Tn): tuple consisting of the types T1, …, Tn, n >= 0

If that was intentional, then should it be assumed that this is some kind of [unit type](https://en.wikipedia.org/wiki/Unit_type) (e.g. like `None` in Python or `()` in Haskell)?

Additionally, if it's correct to see zero-length tuples as unit types, how should we support that?  I suppose an encoder for the unit type could just encode `b'\x00'` in every case and just ignore whatever Python value it is given to encode.  A decoder could also just return `None` by default in every case for the decoded value but still consume and ignore 256 bits of data.

**Comment by davesque** [comment]
I suppose another approach would be to require that the only value in Python which could be encoded to a unit type would be `None` and it would encode to `b'\x00'` padded to 256 bits.  Also, the only binary value which could be decoded as a unit type to the Python value `None` would be the same padded `b'\x00'` value.  I think this way is more aligned with the mathematical definition of a unit type.

And yet another approach could involve using `b''` (0 bytes) as the binary value to and from which the Python `None` would be encoded/decoded.

**Comment by chriseth** [comment]
Python has zero-length tuples, too. I guess that would be the canonical corresponding value. The encoding is the empty byte string.

**Comment by davesque** [comment]
I suppose I figured that, if a 0-tuple is intended to represent a "unit" value, then `None` is actually the best semantic (and most memory efficient) equivalent in Python. Either way works for me though.

**Comment by davesque** [comment]
Oh.  Never mind about the memory thing.  CPython is apparently smart and only ever stores one instance of the 0-tuple in memory.  Honestly, if that's the case, I don't really care about the semantic business as much.
