### ISSUE TITLE
Should remove support for `ureal` and `real` types?

### ISSUE THREAD

**Issue by davesque** [ApeWorX/eth-abi#50]
### What was wrong?

I'm not sure if anything is still using the `ureal` and `real` types but they seem pretty old and it would be nice to clear out some code.

### How can it be fixed?

Should delete code relating to those types.

**Comment by pipermerriam** [comment]
I think dropping this support is ok. I just ran a quick search on https://github.com/allenday/github-solidity-all and there don't appear to be any contracts using the `real` or `ureal` types.

It'd be good to first deprecate and then we can drop in the next major point release.

**Comment by carver** [comment]
:+1: Also no mention of `real` here: http://solidity.readthedocs.io/en/v0.4.22/abi-spec.html#types

Neat link @pipermerriam

**Comment by davesque** [comment]
@pipermerriam @carver 

To be clear, we would be removing the coders as well as supporting functions such as this one: https://github.com/ethereum/eth-abi/blob/master/eth_abi/utils/numeric.py#L68-L76

The upcoming major release proposed by @carver snuck up on me a bit.  I probably should have issued a release with a deprecation for this feature and its supporting functions beforehand.  Is there any chance we can forgo the deprecation since it seems no one is using this feature?

**Comment by dylanjw** [comment]
Maybe its ok, if we are planning to maintain v1 for another cycle, since v2 introduces a breaking change with the string type decoding.

**Comment by pipermerriam** [comment]
@dylanjw 's suggestion seems viable.  The `1.x` line will remain supported for a little while and we can drop these entirely in the `2.x` line.

**Comment by davesque** [comment]
Sweet.  I'll make a PR for this then.
