### ISSUE TITLE
Use simple coder class instantiation instead of on-the-fly subclassing for particular types?

### ISSUE THREAD

**Issue by davesque** [ApeWorX/eth-abi#53]
### What was wrong?

Coder classes currently use programmatic subclassing via the built-in `type` function as an intermediate step toward creating a callable which performs the actual encoding/decoding of values:

https://github.com/ethereum/eth-abi/blob/master/eth_abi/encoding.py#L62
https://github.com/ethereum/eth-abi/blob/master/eth_abi/decoding.py#L41

### How can it be fixed?

Would it be simpler to just pass in coder settings as keyword arguments to an `__init__` method on coder classes?  So something like this:

```python
class BaseEncoder(BaseCoder):
    def __init__(self, **kwargs):
        cls = type(self)
        
        for key, value in kwargs.items():
            if not hasattr(cls, key):
                raise AttributeError(
                    'Property {key} not found on {cls_name} class. '
                    '`{cls_name}.__init__` only accepts keyword arguments which are '
                    'present on the {cls_name} class.'.format(
                        key=repr(key),
                        cls_name=cls.__name__,
                    )
                )
            
            setattr(self, key, value)

        self.validate()

    ...
```

### Disclaimer

If there's a particular reason that this approach was chosen, then just ignore me 😄 .

**Comment by davesque** [comment]
@carver @pipermerriam Any thoughts on this?

**Comment by pipermerriam** [comment]
@davesque no reason I see to not pursue this approach.  Previous pattern was probably borrowed from elsewhere (maybe django class-based-views?) and I'm sure there are good other ways to to do this.

**Comment by carver** [comment]
No objections @davesque

**Comment by davesque** [comment]
Nice.  I think then I'll probably do this as part of the work with moving validation into the coder classes.

**Comment by davesque** [comment]
Closed on accident.
