### ISSUE TITLE
Missing fixed type

### ISSUE THREAD

**Issue by hackaugusto** [ApeWorX/eth-abi#6]
### What was wrong?

Solidity added the `fixed` type back in version 0.3 [ref](https://github.com/ethereum/solidity/blob/develop/Changelog.md#030-2016-03-11)

This library uses a vendored version prior to the patches that changed from real to fixed.

### How was it fixed?

Update the vendored code

#### Cute Animal Picture

![bat](https://cloud.githubusercontent.com/assets/310139/20119367/6523ebf4-a5ef-11e6-9a57-b6ff98dc63f3.jpg)

**Comment by pipermerriam** [comment]
Thanks for reporting this.  I started into it here: https://github.com/pipermerriam/ethereum-abi-utils/pull/7

**Comment by pipermerriam** [comment]
This is done.
