### ISSUE TITLE
Add support for non-standard packed mode

### ISSUE THREAD

**Issue by davesque** [ApeWorX/eth-abi#67]
### What was wrong?

We should add support for non-standard packed mode as described in the solidity ABI spec here: https://solidity.readthedocs.io/en/develop/abi-spec.html#non-standard-packed-mode

### How can it be fixed?

I imagine support could be added in the form of another encoding function which could be imported by doing `from eth_abi import encode_packed` or something like it.  There is no need for a corresponding decoding function since the format is ambiguous and not parsable.

The `encode_packed` function would probably need to use a separate `packed_registry` as well as separate packed coder classes which would be routed by that registry.

**Comment by Uxio0** [comment]
Would be very useful now that `abi.encode_packed` will be mandatory in solidity before calling keccak on data.

**Comment by relyt29** [comment]
Is this pushed to Pypi? I can't seem to use it from the pip package (1.2.2)

Edit: Looks like this is released in the 2.0 version, but the pre-releases are on pypi. Guess I'll be using those then >.<
