### ISSUE TITLE
decoding tx input data

### ISSUE THREAD

**Issue by owocki** [ApeWorX/eth-abi#80]
* Version: 1.1.1
* Python: 3.5
* OS: linux

### What was wrong?

hey yall, question for you

in https://eth-abi.readthedocs.io/en/stable/decoding.html , i see 

```
>>> decode_single('uint256', '0x0000000000000000000000000000000000000000000000000000000000003039')
12345
```

the first param is type, which is labeled uint256, but i see the 2nd param is a `str` despite the first input being `uint256' 

are the docs wrong?

for context, i am trying to use this lib to

```
ipdb> decode_single('uint256','0x1e688c1400000000000000000000000000000000000000000000000000000000000002b7000000000
000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000
0002e516d50413441646154745867423943596a394d5545505578745a4d5a6d334d7469656b676e444a695a793275557a00000000000000000
0000000000000000000' )
*** TypeError: The `data` value must be of bytes type.  Got <class 'str'>
```

but i get a type error

**Comment by owocki** [comment]
i believe the docs must be wrong bc just pasting the code into the interpreter on my local i get

```
ipdb> decode_single('uint256', '0x0000000000000000000000000000000000000000000000000000000000003039')

*** TypeError: The `data` value must be of bytes type.  Got <class 'str'>
```

**Comment by pipermerriam** [comment]
Yes, likely incorrect docs.  We've generally dropped *detection* of hex strings across the board in our libraries.  Try using the binary representation of that hex value.

**Comment by stefanmendoza** [comment]
@owocki looks like the docs were updated in this PR:
https://github.com/ethereum/eth-abi/pull/73
