### ISSUE TITLE
Remove `encode_abi` and `decode_abi` and remove `_single` suffix from other coding functions

### ISSUE THREAD

**Issue by davesque** [ApeWorX/eth-abi#84]
### What was wrong?

The `encode_abi` and `decode_abi` functions (found [here](https://github.com/ethereum/eth-abi/blob/master/eth_abi/abi.py#L55-L74) and [here](
https://github.com/ethereum/eth-abi/blob/master/eth_abi/abi.py#L136-L160)) do not really serve a useful purpose any more.  For example, the following invocations are equivalent:
```python
In [1]: from eth_abi import *

In [2]: encode_single('(int,int)', (1, 2))
Out[2]: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02'

In [3]: encode_abi(('int', 'int'), (1, 2))
Out[3]: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02'
```

### How can it be fixed?

Perhaps we should remove `encode_abi` and `decode_abi` and rename `encode_single` and `decode_single` to `encode` and `decode` respectively?

This could also match Solidity's own API better: https://solidity.readthedocs.io/en/v0.4.24/units-and-global-variables.html?highlight=abi#abi-encoding-functions

**Comment by pipermerriam** [comment]
If we're to do this, it should be done ASAP as part of  v2 as well as a v1.x release formally raising a deprecation warning on these methods.  I'm :+1: on reducing the API surface area.

**Comment by davesque** [comment]
@pipermerriam That was my thinking with creating this and a couple of other issues right now.  I'm thinking of the things I'd like to see in the v2 release.

**Comment by carver** [comment]
:+1: on reducing to a single `encode()` method.

I slightly prefer the `('int', 'int')` format for the ABI types argument. It's parallel to the way the values are being passed in. The tuple format is used in a few places in web3, like (pseudocode):

```py
types = get_abi_types()
vals = get_vals()
encoded = encode_abi(types, vals)
```

Which is made less parallel, and a tiny bit more awkward, with:

```py
types = get_abi_types()
vals = get_vals()
joint_types = '(%s)' % ','.join(types)
encoded = encode_abi(joint_types, vals)
```

**Comment by carver** [comment]
Maybe supporting both is easy enough :+1:, but I prefer the tuple if we only use one.

**Comment by pipermerriam** [comment]
Since `eth-abi` is considered low level, lets try for a *single* API rather than trying to support multiple input formats.
