### ISSUE TITLE
Type strings only for `encode_single` and `decode_single`

### ISSUE THREAD

**Issue by davesque** [ApeWorX/eth-abi#86]
### What was wrong?

The `encode_single` and `decode_single` functions currently accept either a type string or a type tuple to identify the type that is being worked with.  It seems preferable that a type string is all that should be accepted since type tuples are simple converted to type strings internally and an additional type check is performed on the input which could become costly if it ends up in a critical path.

### How can it be fixed?

We should consider changing `encode_single` and `decode_single` to only accept type strings and also remove the `collapse_type` utility function.  Since this function is extremely simple in nature, it can be manually copied to and used in whatever contexts it is still needed (such as in web3.py code).

**Comment by davesque** [comment]
This is loosely related to issue #84 .

**Comment by davesque** [comment]
This is loosely related to issue #85 since removing both `collapse_type` and `process_type` would eliminate the `utils.parsing` module.

**Comment by davesque** [comment]
Created PR #88 in case we decide to make this change.

**Comment by fselmo** [comment]
Closed by #85, #88
