### ISSUE TITLE
Support for arrays of variable length types is broken

### ISSUE THREAD

**Issue by Arachnid** [ApeWorX/eth-abi#93]
Here's the canonical way (per Solidity, at least) to encode `(bytes[]("0xf8a8fd6d", "0xf8a8fd6d"))`:

```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000040
0000000000000000000000000000000000000000000000000000000000000080
0000000000000000000000000000000000000000000000000000000000000004
f8a8fd6d00000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000004
f8a8fd6d00000000000000000000000000000000000000000000000000000000
```

Broken down:

 - 0x00: A head component, consisting of an offset for the tail data (0x20)
 - 0x20: The tail of the array, specifying its length (2)
 - 0x40: The head component of the first element of the array: the offset for the tail data, relative to the start of the current tail data (0x40 + 0x40 = 0x80)
 - 0x60: The head component of the first element of the array: the offset for the tail data, relative to the start of the current tail data (0x80 + 0x40 = 0xC0)
 - 0x80: The length of the first array element (4)
 - 0xA0: The first array element (0xf8a8fd6d)
 - 0xC0: The length of the second array element (4)
 - 0xE0: The second array element (0xf8a8fd6d)

This is most easily thought of as a recursive encoding: The tail data for the first (and in this case, only) element of the ABI is the entire ABI encoding of that element.

In contrast, this library presently produces the current output:

```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000002
0000000000000000000000000000000000000000000000000000000000000004
f8a8fd6d00000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000004
f8a8fd6d00000000000000000000000000000000000000000000000000000000
```

The head element, and the length of the array are correct, but then array elements are packed tightly, without the correct head/tail recursive encoding.

**Comment by carver** [comment]
Thanks @Arachnid - I wish all bug reports were this detailed! :grinning: The good news is that this came up already, so it looks like the change is nearly merged in #92.

I marked that PR as closing this issue, so there will be an update when it's merged. If you'd like, I can also ping you when web3.py gets deployed with the eth-abi version that includes #92.

**Comment by pipermerriam** [comment]
Also, I believe that @davesque is going to be submitting a PR to `ethereum/tests` to increase the coverage of the testing examples (I think there are current a whopping total of like 5).  We could definitely use some help validating that the examples we submit are truly correct but I suspect that will shake out quickly once other implementations start testing against them.

**Comment by carver** [comment]
Unfortunately, I just realized that this was built into the master (v2) branch which isn't stable, or ready for inclusion into the stable Web3.py release. I'll see if I can backport it.
