### ISSUE TITLE
Figure out why some hypothesis tests are running too slow

### ISSUE THREAD

**Issue by carver** [ApeWorX/eth-abi#96]
### What was wrong?

See the test failure on https://github.com/ethereum/eth-abi/pull/95 and the subsequent patchup: https://github.com/ethereum/eth-abi/pull/95/commits/f0bf403639ceef5c09838037fe48a3029e81386d

### How can it be fixed?

:man_shrugging:

**Comment by davesque** [comment]
Just made a PR for this with a fix that is probably more effective.  I'm pretty sure the issue was that there was a recursive hypothesis strategy which could generate up to 100 leaves on each level.
